server:
  port: 8999

spring:
  application:
    name: API-CARD
  config:
    import:
      - nacos:api-common.yaml
      - nacos:api-card.yaml
  cloud:
    compatibility-verifier:
      enabled: false
    nacos:
      server-addr: 10.10.10.10
      config:
        group: collisto
        namespace: test
        file-extension: yaml
      discovery:
        group: collisto
        metadata:
          version: v1
        namespace: test
