server:
  port: 8888

spring:
  application:
    name: API-GATEWAY
  config:
    import:
      - nacos:api-gateway.yaml
  cloud:
    compatibility-verifier:
      enabled: false
    nacos:
      server-addr: 10.10.10.10
      config:
        group: collisto
        namespace: test
        file-extension: yaml
      discovery:
        group: collisto
        namespace: test
        enabled: true
        register-enabled: true
        metadata:
          version: v1
ribbon:
  nacos:
    enabled: false