server:
  port: 8888

spring:
  application:
    name: API-GATEWAY
  config:
    import: nacos:api-gateway.yaml
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
    nacos:
      server-addr:
      config:
        group:
        namespace: test
        file-extension: yaml
      discovery:
        group:
        namespace: test
        enabled: true
        register-enabled: true
        metadata:
          version: v1


ribbon:
  nacos:
    enabled: false