server:
  port: 8899

spring:
  application:
    name: API-AUTH
  config:
    import: nacos:api-common.yaml
  cloud:
    compatibility-verifier:
      enabled: false
    nacos:
      server-addr: 10.10.10.10
      config:
        group: collisto
        namespace: test
        file-extension: yaml
      discovery:
        group: collisto
        metadata:
          version: v1
        namespace: test