server:
  port: 8899

spring:
  application:
    name: API-AUTH
  cloud:
    compatibility-verifier:
      enabled: false
    loadbalancer:
      ribbon:
        enabled: false
    nacos:
      server-addr: 10.10.10.10
      discovery:
        group: collisto
        metadata:
          version: v1
        namespace: test

ribbon:
  nacos:
    enabled: false
