server:
  port: 8899

spring:
  application:
    name: API-AUTH
  cloud:
    compatibility-verifier:
      enabled: false
    nacos:
      discovery:
        server-addr:
        group:
        metadata:
          version: v1
        namespace: test

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always


